const SVG_PATH_CHARS = /^[MmZzLlHhVvCcSsQqTtAa0-9.,+\-\sEe]+$/;

export const SAMPLE_ICONS = Object.freeze({
  home: { path: "M2 12 12 3l10 9h-3v9h-5v-6h-4v6H5v-9z", viewBox: "0 0 24 24" },
  lightbulb: { path: "M9 21h6v-1H9zm3-19a7 7 0 0 0-4 12.744c.6.45 1 .955 1 1.756V18h6v-1.5c0-.8.4-1.306 1-1.756A7 7 0 0 0 12 2zm2 12.8v.2h-4v-.2c0-1.54-.75-2.39-1.48-2.94A5 5 0 1 1 17 12a5.5 5.5 0 0 1-1.52 1.86c-.73.55-1.48 1.4-1.48 2.94z", viewBox: "0 0 24 24" },
  thermometer: { path: "M14 14.76V5a2 2 0 1 0-4 0v9.76a4 4 0 1 0 4 0zM12 20a2 2 0 0 1-1-3.73V5a1 1 0 1 1 2 0v11.27A2 2 0 0 1 12 20z", viewBox: "0 0 24 24" },
});

export function isValidIconName(name) {
  return /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(name);
}

export function suggestIconName(filename, existingIcons = {}) {
  const stem = String(filename).replace(/\.[^.]+$/, "").normalize("NFKD").replace(/[\u0300-\u036f]/g, "");
  const base = stem.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "icon";
  let name = base;
  let suffix = 2;
  while (Object.hasOwn(existingIcons, name)) name = `${base}-${suffix++}`;
  return name;
}

export function validateIconDefinition(icon) {
  if (!icon || typeof icon.path !== "string" || !icon.path.trim() || !SVG_PATH_CHARS.test(icon.path)) {
    throw new TypeError("Icon path must contain SVG path commands only.");
  }
  if (typeof icon.viewBox !== "string") throw new TypeError("Icon viewBox is required.");
  const values = icon.viewBox.trim().split(/[\s,]+/).map(Number);
  if (values.length !== 4 || values.some((value) => !Number.isFinite(value)) || values[2] <= 0 || values[3] <= 0) {
    throw new TypeError("Icon viewBox must contain four finite values and positive dimensions.");
  }
  return { path: icon.path.trim(), viewBox: values.join(" ") };
}

export function validateIconCollection(collection) {
  if (!collection || typeof collection !== "object" || Array.isArray(collection)) {
    throw new TypeError("Icon collection must be an object.");
  }
  const entries = Object.entries(collection);
  if (!entries.length) throw new TypeError("At least one icon is required.");
  const result = {};
  for (const [name, icon] of entries) {
    if (!isValidIconName(name)) throw new TypeError(`Invalid icon name: ${name}`);
    result[name] = validateIconDefinition(icon);
  }
  return result;
}

export function createIconsetSource(collection) {
  const icons = validateIconCollection(collection);
  const safeJson = JSON.stringify(icons, null, 2)
    .replaceAll("<", "\\u003c")
    .replaceAll(">", "\\u003e")
    .replaceAll("&", "\\u0026");
  return `// Generated by ATLAS Icon Studio. Add as a Home Assistant frontend resource.\nwindow.customIconsets = window.customIconsets || {};\nwindow.customIconsets["atlas"] = async (iconName) => {\n  const icons = ${safeJson};\n  return icons[iconName];\n};\n`;
}

export function parseIconsetSource(source) {
  if (typeof source !== "string" || source.length > 64 * 1024 * 1024) {
    throw new TypeError("Icon set source is missing or too large.");
  }
  const match = source.match(/^\s*(?:\/\/ Generated by ATLAS Icon Studio\. Add as a Home Assistant frontend resource\.\s*)?window\.customIconsets\s*=\s*window\.customIconsets\s*\|\|\s*\{\s*\};\s*window\.customIconsets\[\s*["']atlas["']\s*\]\s*=\s*async\s*\(\s*iconName\s*\)\s*=>\s*\{\s*const\s+icons\s*=\s*(\{[\s\S]*?\})\s*;\s*return\s+icons\s*\[\s*iconName\s*\]\s*;\s*\};\s*$/);
  if (!match) throw new TypeError("Unsupported icon set source.");
  return validateIconCollection(JSON.parse(match[1]));
}

export function createSvgSource(icon, title) {
  const { path, viewBox } = validateIconDefinition(icon);
  const safeTitle = String(title).replace(/[<>&"']/g, "");
  return `<?xml version="1.0" encoding="UTF-8"?>\n<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}" role="img" aria-label="${safeTitle}"><path d="${path}" fill="currentColor"/></svg>\n`;
}

export function createCollectionBackup(collection) {
  return {
    kind: "atlas.icon-studio.collection",
    schemaVersion: 1,
    icons: validateIconCollection(collection),
  };
}

export function parseCollectionBackup(text) {
  const document = JSON.parse(text);
  if (document?.kind !== "atlas.icon-studio.collection" || document.schemaVersion !== 1) {
    throw new TypeError("Unsupported icon collection format.");
  }
  return validateIconCollection(document.icons);
}
